// Generated by CoffeeScript 1.4.0
(function() {

  console.log('app start');

  document.onpaste = function(event) {
    var blob, item, items, reader;
    items = event.clipboardData.items;
    console.log(JSON.stringify(items));
    if ((item = items[1]) && /^image/.test(item['type'])) {
      blob = item.getAsFile();
      reader = new FileReader;
      reader.readAsDataURL(blob);
      reader.onload = function(event) {
        var binaryString, button;
        console.log(event.target.result);
        binaryString = event.target.result;
        button = $('.add_media_type_2_photo')[0];
        console.log(button);
        if (button.click()) {
          return console.log('add_media_type_2_photo click');
        }
      };
      return reader.readAsBinaryString(blob);
    }
  };

}).call(this);
